apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-ceaennqx
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-ceaennqx:6cf6ce9506cb8611fc9418a9e7381aa2565cd430@sha256:453a6ac8e1e2ae66836df55375ebe7033671dced25685cc25b3d5a5df5987140
        name: container-image  
